# config.yaml

mysql:
  host: host
  port: 3306
  user: user
  password: password
  database: database

mongodb:
  host: host
  port: 27017
  user: user
  password: password
  database: database
  collection: collection
